export const DEPARTMENT_ROLES: Record<string, string[]> = {
  'Carpentry': [
    'Senior Carpenter',
    'Carpenter',
    'Junior Carpenter',
    'Carpenter Helper',
  ],
  'Electrical': [
    'Electrician',
    'Senior Electrician',
    'Electrical Helper',
    'Furniture Electrician',
    'Wiring Technician',
    'LED Technician',
  ],
  'Plumbing': [
    'Plumber',
    'Senior Plumber',
    'Plumbing Helper',
  ],
  'POP / Gypsum / False Ceiling': [
    'POP Worker',
    'POP Helper',
    'Gypsum Worker',
    'False Ceiling Worker',
    'Gypsum Installer',
    'Putty Worker',
  ],
  'Masonry / Construction': [
    'Mason',
    'Tile Worker',
    'Tile Helper',
    'Civil Worker',
    'Construction Helper',
  ],
  'Interior / Installation': [
    'Furniture Installer',
    'Modular Furniture Installer',
    'Interior Worker',
    'Site Supervisor',
    'Installation Helper',
    'Measurement Technician',
  ],
  'Glass / Aluminium / Metal': [
    'Glass Worker',
    'Glass Fitter',
    'Aluminium Worker',
    'Welder',
    'Metal Fabricator',
    'Steel Worker',
    'Grinder',
  ],
  'Design': [
    'Furniture Designer',
    'Interior Designer',
    '3D Designer',
    'CAD Designer',
    'Measurement Executive',
  ],
  'Management / Office': [
    'Supervisor',
    'Production Supervisor',
    'Site Supervisor',
    'Store Manager',
    'Accountant',
    'HR / Admin',
    'Office Assistant',
    'Manager',
  ],
  'General Helpers': [
    'General Helper',
    'Factory Helper',
    'Workshop Helper',
    'Site Helper',
    'Cleaning Worker',
    'Packing Worker',
    'Packaging Helper',
    'Material Helper',
  ],
};

export const DEPARTMENTS = Object.keys(DEPARTMENT_ROLES);
