const STATUS_CLASS: Record<string, string> = {
  paid: 'ahf-b-paid',
  delivered: 'ahf-b-delivered',
  approved: 'ahf-b-approved',
  active: 'ahf-b-active',
  'in stock': 'ahf-b-instock',
  pending: 'ahf-b-pending',
  'new order': 'ahf-b-new',
  new: 'ahf-b-new',
  processing: 'ahf-b-processing',
  shipped: 'ahf-b-shipped',
  cancelled: 'ahf-b-cancelled',
  rejected: 'ahf-b-rejected',
  'out of stock': 'ahf-b-outofstock',
  draft: 'ahf-b-draft',
  contacted: 'ahf-b-processing',
  site_visit: 'ahf-b-pending',
  'site visit': 'ahf-b-pending',
  proposal: 'ahf-b-processing',
  quotation: 'ahf-b-draft',
  won: 'ahf-b-approved',
  'won (legacy)': 'ahf-b-approved',
  lost: 'ahf-b-cancelled',
  converted: 'ahf-b-approved',
  scheduled: 'ahf-b-pending',
  completed: 'ahf-b-approved',
  rescheduled: 'ahf-b-processing',
  todo: 'ahf-b-pending',
  in_progress: 'ahf-b-processing',
  'in progress': 'ahf-b-processing',
  done: 'ahf-b-approved',
  punched_in: 'ahf-b-active',
  working: 'ahf-b-active',
  'working on-site': 'ahf-b-active',
  absent: 'ahf-b-cancelled',
  inactive: 'ahf-b-cancelled',
  manual: 'ahf-b-processing',
  sent: 'ahf-b-pending',
  partial: 'ahf-b-processing',
  procurement: 'ahf-b-processing',
  execution: 'ahf-b-processing',
  finishing: 'ahf-b-processing',
  planning: 'ahf-b-pending',
  design: 'ahf-b-pending',
  on_hold: 'ahf-b-cancelled',
  'on hold': 'ahf-b-cancelled',
};

export default function StatusBadge({ status }: { status: string }) {
  const key = String(status || '').toLowerCase();
  const cls = STATUS_CLASS[key] || 'ahf-b-default';
  return <span className={`ahf-badge ${cls}`}>{status || '—'}</span>;
}
